# Generated by Django 5.0.6 on 2024-07-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='location',
            field=models.CharField(default=2000, max_length=30),
            preserve_default=False,
        ),
    ]
